[project]
name = "day-68-flask-auth"
version = "0.1.0"
description = "Day 68 auth demo"
requires-python = ">=3.12,<3.13"
dependencies = [
  "flask",  # "flask==3.0.0",
  "Werkzeug==3.0.3",
  "flask_sqlalchemy==3.1.1",
  "SQLAlchemy",  # "SQLAlchemy==2.0.32",
  "Flask-Login==0.6.3",
  "Bootstrap_Flask==2.3.3",
  "Flask_CKEditor==0.5.1",
  "Flask_Login==0.6.3",
  "Flask-Gravatar==0.5.0",
  "Flask_WTF==1.2.1",
  "WTForms==3.0.1",
  "Werkzeug",  # "Werkzeug==3.0.0",
  "Flask==2.3.2",
  "flask_sqlalchemy==3.1.1",
  "SQLAlchemy==2.0.25",
  "gunicorn==21.2.0",
  "psycopg2-binary==2.9.9",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
exclude = ["static", "templates", "instance"]
